/* See https://docs.rs/riscv-rt/latest/riscv_rt/ */
MEMORY
{
  FLASH : ORIGIN = 0x80000000, LENGTH = 32M
  /* RAM : ORIGIN = 0x80000000, LENGTH = 8K */
}

REGION_ALIAS("REGION_TEXT", FLASH);
REGION_ALIAS("REGION_RODATA", FLASH);
REGION_ALIAS("REGION_DATA", FLASH);
REGION_ALIAS("REGION_BSS", FLASH);
REGION_ALIAS("REGION_HEAP", FLASH);
REGION_ALIAS("REGION_STACK", FLASH);
